### ISSUE TITLE
charm assumes VMs/containers run in machine.slice, hardcodes system.slice to 4G

### ISSUE THREAD

**Issue by vmpjdc** [storpool/charm-storpool-block#3]
On one of our Ubuntu 16.04 LTS OpenStack deployments with StorPool 18.01 (package version 18.01.305.1f15bc4-1ubuntu1) system.slice is limited to 4G. These machines are nova-compute hosts with over 500G of memory. Since all of the nova-compute processes run in system.slice, this causes OOMs under negligible load, e.g.:

    neutron-openvsw invoked oom-killer: gfp_mask=0x24000c0, order=0, oom_score_adj=0
    neutron-openvsw cpuset=sysdefault mems_allowed=0-1
    CPU: 22 PID: 1199069 Comm: neutron-openvsw Tainted: G        W  OE   4.4.0-127-generic #153-Ubuntu
    Hardware name: Dell Inc. PowerEdge R730/072T6D, BIOS 2.4.3 01/17/2017
     0000000000000286 6e38fe2c4f39eff5 ffff887de608fc88 ffffffff814001c3
     ffff887de608fd68 ffff887e820daa00 ffff887de608fcf8 ffffffff8121047e
     0000000000000015 ffff887de608fcc8 ffffffff811964ab ffff883dc3980000
    Call Trace:
     [<ffffffff814001c3>] dump_stack+0x63/0x90
     [<ffffffff8121047e>] dump_header+0x5a/0x1c5
     [<ffffffff811964ab>] ? find_lock_task_mm+0x3b/0x80
     [<ffffffff81196a72>] oom_kill_process+0x202/0x3c0
     [<ffffffff81203f74>] ? mem_cgroup_iter+0x204/0x3a0
     [<ffffffff81205fe3>] mem_cgroup_out_of_memory+0x2b3/0x300
     [<ffffffff81206dcd>] mem_cgroup_oom_synchronize+0x33d/0x350
     [<ffffffff81201e20>] ? kzalloc_node.constprop.49+0x20/0x20
     [<ffffffff81197124>] pagefault_out_of_memory+0x44/0xc0
     [<ffffffff8106c622>] mm_fault_error+0x82/0x160
     [<ffffffff8106cae9>] __do_page_fault+0x3e9/0x410
     [<ffffffff8106cb32>] do_page_fault+0x22/0x30
     [<ffffffff81853658>] page_fault+0x28/0x30
    Task in /system.slice/ovs-vswitchd.service killed as a result of limit of /system.slice
    memory: usage 4194304kB, limit 4194304kB, failcnt 30329822

Here's the memory controller config:

    /sys/fs/cgroup/memory/memory.limit_in_bytes                 9223372036854771712
    /sys/fs/cgroup/memory/machine.slice/memory.limit_in_bytes   520551923712
    /sys/fs/cgroup/memory/storpool.slice/memory.limit_in_bytes  1073741824
    /sys/fs/cgroup/memory/system.slice/memory.limit_in_bytes    4294967296
    /sys/fs/cgroup/memory/user.slice/memory.limit_in_bytes      4294967296

It seems that storpool enabled this behaviour:

    $ grep ^ /etc/systemd/system/*/90-MemoryLimit.conf
    /etc/systemd/system/machine.slice.d/90-MemoryLimit.conf:[Slice]
    /etc/systemd/system/machine.slice.d/90-MemoryLimit.conf:MemoryAccounting=true
    /etc/systemd/system/storpool.slice.d/90-MemoryLimit.conf:[Slice]
    /etc/systemd/system/storpool.slice.d/90-MemoryLimit.conf:MemoryAccounting=true
    /etc/systemd/system/system.slice.d/90-MemoryLimit.conf:[Slice]
    /etc/systemd/system/system.slice.d/90-MemoryLimit.conf:MemoryAccounting=true
    /etc/systemd/system/user.slice.d/90-MemoryLimit.conf:[Slice]
    /etc/systemd/system/user.slice.d/90-MemoryLimit.conf:MemoryAccounting=true
    $ dpkg -S /etc/systemd/system/*/90-MemoryLimit.conf
    storpool-cgconfig-18.01: /etc/systemd/system/machine.slice.d/90-MemoryLimit.conf
    storpool-cgconfig-18.01: /etc/systemd/system/storpool.slice.d/90-MemoryLimit.conf
    storpool-cgconfig-18.01: /etc/systemd/system/system.slice.d/90-MemoryLimit.conf
    storpool-cgconfig-18.01: /etc/systemd/system/user.slice.d/90-MemoryLimit.conf
    $ _

I don't see any obviously related config items on the charm.

**Comment by vmpjdc** [comment]
Ah, so it seems the limit is defined here:

    $ cat /etc/cgconfig.d/system.slice.conf 
    group system.slice {
        cpuset {
                cpuset.mems="0";
                cpuset.cpus="3-55";
        }
        memory {
                memory.move_charge_at_immigrate="1";
                memory.use_hierarchy="1";
                memory.limit_in_bytes="4096M";
                memory.memsw.limit_in_bytes="12287M";
        }
    }$ _

and this file is not shipped with any package currently installed, so I assume a component of StorPool created it.

**Comment by vmpjdc** [comment]
Oh, found it. It's hardcoded in the charm:

    def configure_cgroups():
        [...]
        mem_system = 4 * 1024
        [...]
        mem_machine = mem_total - mem_reserved
        tdata.update({
            'mem_system': mem_system,
            'memsw_system': mem_system + total_swap,
        [...]
            'mem_machine': mem_machine,
            'memsw_machine': mem_machine + total_swap,
        })

I guess the assumption is that most things will run in machine.slice? But that's not the case here.

**Comment by vmpjdc** [comment]
VMs and containers will run in machine.slice if systemd-machined is informed about them. However, systemd-container (the Ubuntu package that provides this daemon) is not installed. I set up a test environment with libvirtd and systemd-machined and launched a VM, and the qemu process was assigned to machine.slice. So this seems like it would solve the problem in our environment. Since storpool-block sets up the cgroups on the assumption that VMs and containers will run in machine.slice, it probably makes sense for it to ensure that systemd-machined is installed.

Nevertheless, I still feel that system.slice is undersized for our deployments. A nova-compute host runs a lot of services, and we also deploy a bunch more to manage and maintain the system. The charm should probably autotune this a little based on the size of the machine and/or expose a config item to let us tune it directly. I am happy to split this into a separate issue if you prefer.

**Comment by ppenchev-storpool** [comment]
Hi,

(some more discussion took place in a StorPool Zendesk ticket)

Thanks for reporting this and for your excellent analysis!  The size of the system slice was indeed hardcoded in the charm, but this has changed now with a commit in the https://github.com/storpool/layer-storpool-openstack-integration/pull/2 pull request.  As noted in the Zendesk ticket, the new configuration setting should allow you to tweak the sizes of the cgroup memory slices.

Thanks for your patience and understanding!

Best regards,
Peter
